In [8]:
import numpy as np
import pandas as pd

In [9]:
pd.read_csv('ex.csv')

1   2   3   4
0  5   6   7   8
1  9  10  11  12

In [14]:
names = ['a','b','c','d','message']
pd.read_csv('csv/ex.csv',names = names)

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12  pandas

In [16]:
names = ['a','b','c','d','message']
pd.read_csv('csv/ex.csv',names = names, index_col = 'message')

a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
pandas   9  10  11  12

In [33]:
parsed = pd.read_csv('csv/csv_min.csv', index_col=['key1','key2'])

In [34]:
parsed

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [37]:
ex7 = pd.read_table("csv/ex7.csv")

In [38]:
ex7

a,"b","c"
0      1,"2","3"
1  1,"2","3","4"

In [39]:
import csv
f = open('csv/ex7.csv')
f

<_io.TextIOWrapper name='csv/ex7.csv' mode='r' encoding='cp949'>

In [40]:
reader = csv.reader(f)

for i in reader:
    print(i)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3', '4']


In [42]:
lines = list(csv.reader(open('csv/ex7.csv')))
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3', '4']]

In [43]:
header, values = lines[0], lines[1:]
header
values

[['1', '2', '3'], ['1', '2', '3', '4']]

### 이진데이터 형식

In [49]:
frame = pd.read_csv('csv/ex.csv', names=['a','b','c','d','message'])
frame

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12  pandas

In [54]:
frame.to_pickle('csv/frame_pickle')

In [55]:
pd.read_pickle('csv/frame_pickle')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12  pandas

###  hd5 

In [57]:
store = pd.HDFStore('csv/mydata.h5')

In [59]:
store['obj1'] = frame
store['obj1_col'] = frame['a']

In [61]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: csv/mydata.h5

In [64]:
store['obj1']

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12  pandas

### 데이터베이스와 사용하기

In [65]:
import sqlite3
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""
con = sqlite3.connect('mydata.sqlite')
con.execute(query)
con.commit()

In [66]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [68]:
cursor = con.execute('select * from test')

rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [69]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [70]:
pd.DataFrame(rows, columns = list(zip(*cursor.description))[0])

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [72]:
import pandas.io.sql as sql

pd.read_sql('select * from test', con)

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [73]:
con

In [74]:
from pandas import Series, DataFrame

import pandas as pd
import numpy as np

df1 = DataFrame({'key': ['b','b','a','c','a','a','b'],
                'data1':range(7)})
df2 = DataFrame({'key': ['a','b','d'], 'data2':range(3)})

In [77]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [78]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [79]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [80]:
pd.merge(df1,df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [81]:
df3 = DataFrame({'lkey': ['b','b','a','c','a','a','b'],
                'data3':range(7)})
df4 = DataFrame({'rkey': ['a','b','d'], 'data4':range(3)})
pd.merge(df3,df4, left_on='lkey', right_on='rkey')

lkey  data3 rkey  data4
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [82]:
left = DataFrame({'key': ['a','b','a','a','b','c',],
                 'value':range(6)})
right = DataFrame({'group_val':[3.5, 7] }, index =['a','b'])

In [83]:
left

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [84]:
right

group_val
a        3.5
b        7.0

In [86]:
pd.merge(left,right, left_on = 'key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [87]:
pd.merge(left,right, left_on = 'key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

## 양측이 색인

In [88]:
left2 = DataFrame([[1,2], [3,4], [5,6]], index=['a','c','e'], columns=['Ohio','Nevada'])
right2 = DataFrame([[7,8], [9,10], [11,12], [13,14]], index=['b','c','d','e'], columns=['Missouri','Alabama'])

In [89]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [90]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [93]:
pd.merge(left2, right2, left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
c     3       4         9       10
e     5       6        13       14

In [94]:
pd.merge(left2, right2, left_index=True, right_index=True, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [96]:
left2.join(right2)

Ohio  Nevada  Missouri  Alabama
a     1       2       NaN      NaN
c     3       4       9.0     10.0
e     5       6      13.0     14.0

In [98]:
left2.join(right2, how="outer")

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [100]:
left.join(right, on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

## concat 이어 붙이기

In [105]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
np.concatenate([arr,arr], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
np.concatenate([arr,arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [116]:
s1 = Series([0,1], index=['a','b'])
s2 = Series([2,3,4], index=['c','d','e'])
s3 = Series([5,6], index=['f','g'])

In [118]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [119]:
pd.concat([s1,s2,s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [122]:
pd.concat([s1,s2,s3], keys=['s_one','s_two','s_three']) # 색인

s_one    a    0
         b    1
s_two    c    2
         d    3
         e    4
s_three  f    5
         g    6
dtype: int64

In [126]:
pd.concat([s1,s2,s3], axis=1, keys=['s_one','s_two','s_three']) # 색인

s_one  s_two  s_three
a    0.0    NaN      NaN
b    1.0    NaN      NaN
c    NaN    2.0      NaN
d    NaN    3.0      NaN
e    NaN    4.0      NaN
f    NaN    NaN      5.0
g    NaN    NaN      6.0

In [130]:
df1 = DataFrame(np.arange(6).reshape(3,2), index=['a','b','c'], columns=['one','two'])
df2 = DataFrame(5 + np.arange(4).reshape(2,2), index=['a','c'], columns=['three','four'])

pd.concat([df1,df2] , axis=1, keys=['level1','level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [136]:
pd.concat({'df1':df1, 'df2':df2}, axis=1, names = ["type","index"])

type  df1       df2     
index one two three four
a       0   1   5.0  6.0
b       2   3   NaN  NaN
c       4   5   7.0  8.0

## ignore-index 색인 불필요

In [147]:
df1 = DataFrame(np.random.randn(3,4), columns=['a','b','c','d'])
df1

a         b         c         d
0 -0.666655  0.182566  0.303301  0.577702
1 -0.026745 -0.481736 -2.191118  0.367426
2  1.362533  1.170835 -1.592402  1.237795

In [148]:
df2 = DataFrame(np.random.randn(2,3), columns=['b','d','a'])
df2

b         d         a
0 -1.018574  0.697326 -0.103560
1 -1.128564  0.651998  0.216258

In [150]:
pd.concat([df1,df2])

a         b         c         d
0 -0.666655  0.182566  0.303301  0.577702
1 -0.026745 -0.481736 -2.191118  0.367426
2  1.362533  1.170835 -1.592402  1.237795
0 -0.103560 -1.018574       NaN  0.697326
1  0.216258 -1.128564       NaN  0.651998

In [151]:
pd.concat([df1,df2], ignore_index=True)

a         b         c         d
0 -0.666655  0.182566  0.303301  0.577702
1 -0.026745 -0.481736 -2.191118  0.367426
2  1.362533  1.170835 -1.592402  1.237795
3 -0.103560 -1.018574       NaN  0.697326
4  0.216258 -1.128564       NaN  0.651998

## combine_first

In [152]:
df1 = DataFrame({'a':[1,np.nan,5,np.nan,],
                'b':[np.nan,2,np.nan,6],
                'c': range(2,18,4)})
df2 = DataFrame({'a':[5,4,np.nan,3,7],
                'b':[np.nan,3,4,6,8]})

In [153]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [154]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [155]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

## 재형성 피벗

In [164]:
data = DataFrame(np.arange(6).reshape((2,3)),
                index=pd.Index(['Ohio', 'Colorado'], name='state'),
                columns=pd.Index(['one','two','three'], name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [165]:
type(data)

pandas.core.frame.DataFrame

In [162]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [163]:
type(result)

pandas.core.series.Series

In [166]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [167]:
import seaborn as sns

In [168]:
titanic = sns.load_dataset('titanic')

In [169]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [170]:
type(titanic)

pandas.core.frame.DataFrame

In [175]:
t_pclass = titanic['pclass']

In [176]:
t_sex = titanic['sex']

In [192]:
df_titanic = pd.DataFrame([t_pclass, t_sex], index = ['index=1','index=2'], columns= range(890))
df_titanic

0       1       2       3     4     5     6     7       8       9    \
index=1     3       1       3       1     3     3     1     3       3       2   
index=2  male  female  female  female  male  male  male  male  female  female   

         ...     880   881     882   883   884     885   886     887     888  \
index=1  ...       2     3       3     2     3       3     2       1       3   
index=2  ...  female  male  female  male  male  female  male  female  female   

          889  
index=1     1  
index=2  male  

[2 rows x 890 columns]

In [193]:
s1 = Series([0,1,2,3], index=['a','b','c','d'])
s2 = Series([4,5,6], index=['c','d','e'])


In [194]:
s1

a    0
b    1
c    2
d    3
dtype: int64

In [195]:
s2

c    4
d    5
e    6
dtype: int64

In [211]:
data2 = pd.concat([s1,s2], keys=[1,2], names="n")
data2.unstack()

a    b    c    d    e
n                         
1  0.0  1.0  2.0  3.0  NaN
2  NaN  NaN  4.0  5.0  6.0

In [212]:
data2

n   
1  a    0
   b    1
   c    2
   d    3
2  c    4
   d    5
   e    6
dtype: int64

In [213]:
data2.unstack().stack()

n   
1  a    0.0
   b    1.0
   c    2.0
   d    3.0
2  c    4.0
   d    5.0
   e    6.0
dtype: float64

In [215]:
data2.unstack().stack(dropna=False)

n   
1  a    0.0
   b    1.0
   c    2.0
   d    3.0
   e    NaN
2  a    NaN
   b    NaN
   c    4.0
   d    5.0
   e    6.0
dtype: float64

TypeError: 'DataFrame' object is not callable