In [1]:
import numpy as np

# 배열의 재형성

In [2]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
arr.reshape((4,2)) # 4행 2열 구조로 재형성


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [4]:
arr.reshape((2,4)) # 2행 4열

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr.reshape(4,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
arr.reshape(4,-1).ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
arr.reshape(4,-1).flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [16]:
np.concatenate([arr1,arr2]) # axis = 0 default

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.concatenate([arr1,arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [18]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
f, s, t = np.split(np.vstack([arr1,arr2]), [1,3] )

In [24]:
f, s, t

(array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12]]))

In [25]:
arr = np.arange(6)

In [27]:
arr1 = arr.reshape((3,2))
arr2 = np.random.randn(3,2)

In [28]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
arr2

array([[ 0.38365586, -2.10593099],
       [ 1.49941289, -0.44976316],
       [ 1.64585094, -0.22680532]])

In [30]:
np.r_[arr1,arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.38365586, -2.10593099],
       [ 1.49941289, -0.44976316],
       [ 1.64585094, -0.22680532]])

In [31]:
np.c_[arr1,arr2]

array([[ 0.        ,  1.        ,  0.38365586, -2.10593099],
       [ 2.        ,  3.        ,  1.49941289, -0.44976316],
       [ 4.        ,  5.        ,  1.64585094, -0.22680532]])

In [32]:
np.c_[np.r_[arr1,arr2],arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 0.38365586, -2.10593099,  3.        ],
       [ 1.49941289, -0.44976316,  4.        ],
       [ 1.64585094, -0.22680532,  5.        ]])

In [37]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [38]:
arr

array([0, 1, 2, 3, 4, 5])

In [39]:
arr.repeat(5)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5])

In [43]:
arr.repeat([2,3,4,5,6,1])

array([0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5])

In [44]:
arr = np.random.randn(2,2)

In [45]:
arr

array([[-1.61420355,  0.04090999],
       [-0.47974348,  1.13375552]])

In [48]:
arr.repeat(2, axis=1).shape

(2, 4)

In [55]:
arr

array([[-1.61420355,  0.04090999],
       [-0.47974348,  1.13375552]])

In [56]:
arr.shape

(2, 2)

In [53]:
np.tile(arr, 2)

array([[-1.61420355,  0.04090999, -1.61420355,  0.04090999],
       [-0.47974348,  1.13375552, -0.47974348,  1.13375552]])

In [54]:
np.tile(arr, 2).shape

(2, 4)

In [57]:
np.tile(arr, (2,1))

array([[-1.61420355,  0.04090999],
       [-0.47974348,  1.13375552],
       [-1.61420355,  0.04090999],
       [-0.47974348,  1.13375552]])

In [58]:
np.tile(arr, (2,1)).shape

(4, 2)

In [52]:
np.tile(arr, (3,2))

array([[-1.61420355,  0.04090999, -1.61420355,  0.04090999],
       [-0.47974348,  1.13375552, -0.47974348,  1.13375552],
       [-1.61420355,  0.04090999, -1.61420355,  0.04090999],
       [-0.47974348,  1.13375552, -0.47974348,  1.13375552],
       [-1.61420355,  0.04090999, -1.61420355,  0.04090999],
       [-0.47974348,  1.13375552, -0.47974348,  1.13375552]])

In [59]:
np.tile(arr, (3,2)).shape

(6, 4)

In [60]:
arr = np.arange(10)* 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [61]:
inds = [7,1,2,6]
inds

[7, 1, 2, 6]

In [62]:
arr[inds] # 7번째, 1번째, 2번째, 6번째 원소

array([700, 100, 200, 600])

In [63]:
arr.take(inds)

array([700, 100, 200, 600])

In [64]:
arr.put(inds, 42)

In [65]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [66]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [67]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [68]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [69]:
arr = np.random.randn(4,3)
arr

array([[-0.38581893, -1.13624379, -0.54760875],
       [-0.97551519, -0.541906  ,  0.15509803],
       [-0.51660145,  0.6694879 ,  0.19903525],
       [ 0.85473238, -0.38719018, -1.07016091]])

In [72]:
arr[0].mean()

-0.6898904862004901

In [73]:
arr[1].mean()

-0.4541077202278436

In [74]:
arr[2].mean()

0.11730723231811252

In [76]:
arr[3].mean()

-0.20087290205858763

In [77]:
arr.mean(0)

array([-0.2558008 , -0.34896302, -0.31590909])

In [78]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.13001813, -0.78728077, -0.23169966],
       [-0.71971439, -0.19294299,  0.47100713],
       [-0.26080066,  1.01845092,  0.51494435],
       [ 1.11053318, -0.03822716, -0.75425182]])

In [83]:
demeaned.mean(0)

array([ 0.00000000e+00,  5.55111512e-17, -2.77555756e-17])

In [84]:
arr

array([[-0.38581893, -1.13624379, -0.54760875],
       [-0.97551519, -0.541906  ,  0.15509803],
       [-0.51660145,  0.6694879 ,  0.19903525],
       [ 0.85473238, -0.38719018, -1.07016091]])

In [86]:
row_means = arr.mean(1)
row_means

array([-0.68989049, -0.45410772,  0.11730723, -0.2008729 ])

In [88]:
row_means.reshape(4,-1)

array([[-0.68989049],
       [-0.45410772],
       [ 0.11730723],
       [-0.2008729 ]])

In [89]:
demeaned = arr - row_means.reshape(4,-1)

In [91]:
demeaned.mean(1)

array([ 0.00000000e+00, -3.70074342e-17,  0.00000000e+00,  0.00000000e+00])

In [92]:
arr = np.zeros((4,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
arr[:] = 5

In [94]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [95]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [96]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [98]:
arr[:2] = [[-1.37],[0.5098]]
arr

array([[-1.37  , -1.37  , -1.37  ],
       [ 0.5098,  0.5098,  0.5098],
       [ 0.44  ,  0.44  ,  0.44  ],
       [ 1.6   ,  1.6   ,  1.6   ]])

In [104]:
d_type = [('x', np.float64), ('y', np.int32)]
d_type

[('x', numpy.float64), ('y', numpy.int32)]

In [100]:
type(dtype)

list

In [106]:
d_type = [('x', np.float64), ('y', np.int32)]

sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=d_ytpe)
sarr

NameError: name 'd_ytpe' is not defined

In [108]:
arr = np.random.randn(6)
arr

array([ 0.15983786,  0.3646375 ,  0.97312218, -0.70710183, -0.35173079,
        0.08001334])

In [109]:
arr.sort()

In [110]:
arr

array([-0.70710183, -0.35173079,  0.08001334,  0.15983786,  0.3646375 ,
        0.97312218])

In [111]:
arr = np.random.randn(3, 5)
arr

array([[ 0.49401277,  1.86669655,  1.39322246,  0.33396903,  1.74883732],
       [-1.43783195, -0.20327654,  0.1948061 ,  0.47163049, -0.44655479],
       [ 0.57159709, -0.82174054, -0.22405973,  0.44801635,  0.26198384]])

In [113]:
arr[:, 0].sort()

In [114]:
arr

array([[-1.43783195,  1.86669655,  1.39322246,  0.33396903,  1.74883732],
       [ 0.49401277, -0.20327654,  0.1948061 ,  0.47163049, -0.44655479],
       [ 0.57159709, -0.82174054, -0.22405973,  0.44801635,  0.26198384]])

In [115]:
arr = np.random.randn(6)
arr

array([-6.80460838e-02, -1.69827249e+00, -2.35705978e-06, -7.44728014e-01,
       -1.07536118e+00,  4.24359482e-01])

In [116]:
np.sort(arr) # 복사본

array([-1.69827249e+00, -1.07536118e+00, -7.44728014e-01, -6.80460838e-02,
       -2.35705978e-06,  4.24359482e-01])

In [117]:
arr

array([-6.80460838e-02, -1.69827249e+00, -2.35705978e-06, -7.44728014e-01,
       -1.07536118e+00,  4.24359482e-01])

In [124]:
arr = np.random.randn(3,5)
arr

array([[ 1.01481262, -1.62683287, -0.03280101,  2.37096277,  2.13546696],
       [ 0.95641268, -0.82808417,  0.19471668, -0.24819404, -0.42508317],
       [ 0.30378571, -0.19660348,  0.02898071,  0.74729047,  1.19951369]])

In [130]:
arr.sort(axis=1)
arr

array([[-1.62683287, -0.42508317, -0.24819404,  0.19471668,  0.95641268],
       [-0.82808417, -0.03280101,  0.30378571,  0.74729047,  1.19951369],
       [-0.19660348,  0.02898071,  1.01481262,  2.13546696,  2.37096277]])

In [135]:
arr[:, ::-1]

array([[ 0.95641268,  0.19471668, -0.24819404, -0.42508317, -1.62683287],
       [ 1.19951369,  0.74729047,  0.30378571, -0.03280101, -0.82808417],
       [ 2.37096277,  2.13546696,  1.01481262,  0.02898071, -0.19660348]])

In [138]:
values = np.array([5,0,1,3,2])
values

array([5, 0, 1, 3, 2])

In [139]:
indexer = values.argsort()

In [140]:
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [141]:
values[indexer]

array([0, 1, 2, 3, 5])

In [143]:
arr = np.random.randn(3, 5)

In [144]:
arr

array([[ 0.03669536,  0.57643331,  0.32908685, -0.54141944, -0.17711498],
       [ 1.58752072,  0.56335668,  0.72093589, -0.04712265, -0.21132957],
       [-0.99212628, -1.5997357 , -0.72792744,  1.81857051, -0.7642073 ]])

In [145]:
arr[0] = values

In [146]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 1.58752072,  0.56335668,  0.72093589, -0.04712265, -0.21132957],
       [-0.99212628, -1.5997357 , -0.72792744,  1.81857051, -0.7642073 ]])

In [147]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.56335668,  0.72093589, -0.21132957, -0.04712265,  1.58752072],
       [-1.5997357 , -0.72792744, -0.7642073 ,  1.81857051, -0.99212628]])

In [148]:
X = np.array([[8,3,-1,2],
             [3,6,0.8,2],
             [-1,0,5,8],
             [2,2,0,6]])
X

array([[ 8. ,  3. , -1. ,  2. ],
       [ 3. ,  6. ,  0.8,  2. ],
       [-1. ,  0. ,  5. ,  8. ],
       [ 2. ,  2. ,  0. ,  6. ]])

In [155]:
y = X[:, :1]
y

array([[ 8.],
       [ 3.],
       [-1.],
       [ 2.]])

In [156]:
y.T # 전치 

array([[ 8.,  3., -1.,  2.]])

In [160]:
np.dot(y.T , np.dot(X,y))

array([[824.6]])

In [161]:
Xm = np.matrix(X)
Xm

matrix([[ 8. ,  3. , -1. ,  2. ],
        [ 3. ,  6. ,  0.8,  2. ],
        [-1. ,  0. ,  5. ,  8. ],
        [ 2. ,  2. ,  0. ,  6. ]])